import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from backend.app.core.config import settings
from backend.app.core.logging_config import setup_logging, RequestLoggingMiddleware
from backend.app.rag.retriever import retriever
from backend.app.rag.chat_agent import chat_agent, ChatAgentRequest, ChatAgentResponse
from backend.app.engines.triage_engine import (
    triage_engine,
    TriageFormulationInput,
    TriageFormulationOutput
)

# Initialize colorful structured logging
setup_logging()
logger = logging.getLogger("backend.app")

app = FastAPI(
    title=settings.PROJECT_NAME,
    version=settings.VERSION,
    description=settings.DESCRIPTION
)

app.add_middleware(RequestLoggingMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class DossierExportRequest(BaseModel):
    product_name: str
    category_name: str
    jurisdiction: str
    chat_history: List[Dict[str, str]]
    citations: List[Dict[str, Any]]
    triage_result: Optional[Dict[str, Any]] = None

@app.on_event("startup")
async def startup_event():
    logger.info(f"🌿 Starting {settings.PROJECT_NAME} (v{settings.VERSION})...")
    logger.info(f"Connecting to Qdrant at {settings.QDRANT_HOST}:{settings.QDRANT_PORT}...")
    retriever.initialize()
    logger.info("✅ Qdrant collections, PyMuPDF extractors, BM25 indices & Cross-Encoder ready.")

@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": settings.PROJECT_NAME,
        "version": settings.VERSION,
        "collections": [
            settings.QDRANT_COLLECTION_NATIONAL,
            settings.QDRANT_COLLECTION_INTERNATIONAL
        ]
    }

@app.post("/api/chat/", response_model=ChatAgentResponse)
async def chat_endpoint(req: ChatAgentRequest):
    """Conversational Chat Agent endpoint with grounded synthesis, triage & citations."""
    try:
        logger.info(f"💬 Chat Query: '{req.query}' [Jurisdiction: {req.jurisdiction.upper()}]")
        response = chat_agent.process_message(req)
        logger.info(f"🎯 Grounding Confidence: {int(response.confidence_score * 100)}% | Citations: {len(response.citations)}")
        return response
    except Exception as e:
        logger.error(f"Error in chat processing: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/triage/evaluate", response_model=TriageFormulationOutput)
async def evaluate_triage(input_data: TriageFormulationInput):
    """5-Step Formulation Triage Classifier & Posture Evaluator."""
    try:
        logger.info(f"🧪 Triaging formulation: '{input_data.product_name}'")
        result = triage_engine.evaluate(input_data)
        logger.info(f"✅ Category: {result.category} | Patent: {result.patent_status} | ABS: {result.abs_status}")
        return result
    except Exception as e:
        logger.error(f"Error in triage evaluation: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/export/dossier")
async def export_dossier(req: DossierExportRequest):
    """Generates a structured IP Facilitator Handoff Dossier in Markdown format."""
    logger.info(f"📋 Generating IP Facilitator Dossier for '{req.product_name}'...")
    lines = [
        f"# 📋 IP Facilitator Handoff Dossier: {req.product_name}",
        f"**Category**: `{req.category_name}`",
        f"**Jurisdiction Assessed**: `{req.jurisdiction.upper()}`",
        f"**Generated By**: IP-SAKTI Sahayak (Statutory AI Assistant)\n",
        "## 1. Executive Summary & Statutory Posture",
    ]

    if req.triage_result:
        tr = req.triage_result
        lines.append(f"- **Patent Status**: `{tr.get('patent_status')}`")
        lines.append(f"- **Patent Rationale**: {tr.get('patent_rationale')}")
        lines.append(f"- **Biodiversity ABS Status**: `{tr.get('abs_status')}`")
        lines.append(f"- **ABS Rationale**: {tr.get('abs_rationale')}")
        lines.append(f"- **Licensing Regime**: {tr.get('licensing_framework')}\n")
        lines.append("### Mandatory Regulatory Forms:")
        for form in tr.get("licensing_forms", []):
            lines.append(f"  - 📄 {form}")
        lines.append("\n### Compliance Checklist:")
        for item in tr.get("compliance_checklist", []):
            lines.append(f"  - [ ] {item}")
        lines.append("")
    else:
        lines.append("- Evaluated against Patents Act 1970 §3(p), Drugs & Cosmetics Act 1940, and BD Act 2023.\n")

    lines.append("## 2. Conversation Transcript & Grounded Guidance")
    for msg in req.chat_history:
        role = "👤 User" if msg.get("role") == "user" else "🌿 IP-SAKTI Sahayak"
        lines.append(f"### {role}\n{msg.get('content')}\n")

    lines.append("## 3. Statutory References & Official Citations")
    for c in req.citations:
        title = c.get("title", c.get("statute", "Statute"))
        url = c.get("source_url", "https://ipindia.gov.in")
        lines.append(f"- **{title}**: [Official Portal]({url})")

    lines.append(f"\n---\n*Disclaimer: {settings.LEGAL_DISCLAIMER}*")
    dossier_content = "\n".join(lines)
    return {
        "filename": f"IP_Facilitator_Dossier_{req.product_name.replace(' ', '_')}.md",
        "content": dossier_content
    }

# Mount frontend directory for web testing
frontend_dir = settings.BASE_DIR / "frontend"
if frontend_dir.exists():
    app.mount("/static", StaticFiles(directory=str(frontend_dir)), name="static")

@app.get("/")
async def root():
    return {
        "message": "Welcome to IP-SAKTI Sahayak API",
        "web_ui": "/static/index.html",
        "docs": "/docs"
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.app.main:app", host="0.0.0.0", port=8000, reload=True)
